# Generated by Django 4.0.5 on 2022-07-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia_paterna',
            name='fecha_nacimiento',
        ),
    ]
