# Generated by Django 4.0.5 on 2022-07-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_remove_familia_paterna_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia_paterna',
            old_name='edad',
            new_name='anio_nacimiento',
        ),
    ]
