# Generated by Django 4.0.5 on 2022-07-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0003_rename_edad_familia_paterna_anio_nacimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familia_materna',
            new_name='Familia',
        ),
        migrations.DeleteModel(
            name='Familia_paterna',
        ),
    ]
